spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@cluster0.9ctqm.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
  application:
    name: webflux-course